[package]
name = "trust-tlsa"
version = "0.0.1"
authors = ["Andrew McConachie <andrew@depht.com>"]
edition = "2018"

[dependencies]
trust-dns-resolver = { version = "*" } 
structopt = {version = "^0.2", default-features = false }
